# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.templates_dir: '%kernel.project_dir%/templates'
    env(C_REST_CLIENT_ID): ~
    env(C_REST_CLIENT_SECRET): ~
    env(OAUTH_SERVER_URL): ~
    env(C_REST_CURRENT_ENCODING): ~
    env(C_REST_IGNORE_SSL): ~

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Infrastructure\Presentation\TemplateRenderer:
        arguments:
            $templateDir: '%app.templates_dir%'

    App\Domain\Repository\ClientRepositoryInterface:
        alias: App\Infrastructure\Repository\ClientRepository

    App\Infrastructure\Gateway\Transport:
        alias: App\Infrastructure\Gateway\TransportCurl

    App\Infrastructure\Gateway\BitrixApi:
        arguments:
            $urlGenerator: '@App\Application\Gateway\BitrixUrlGenerator'
            $accessTokenRefresher: '@App\Infrastructure\Gateway\AccessTokenRefresher'
            $transport: '@App\Infrastructure\Gateway\TransportCurl'

    App\Infrastructure\Gateway\AccessTokenRefresher:
        arguments:
            $clientId: '%env(C_REST_CLIENT_ID)%'
            $clientSecret: '%env(C_REST_CLIENT_SECRET)%'
#            $urlProvider: '@App\Application\Gateway\AuthUrlProvider'
#            $clientRepository: '@App\Infrastructure\Repository\ClientRepository'
#            $transport: '@App\Infrastructure\Gateway\TransportCurl'

    App\Infrastructure\Gateway\TransportCurl:
        arguments:
            $disableSslVerification: '%env(C_REST_IGNORE_SSL)%'
            $encoding: '%env(C_REST_CURRENT_ENCODING)%'

    App\Application\Gateway\AuthUrlProvider:
        arguments:
            $baseUrl: '%env(OAUTH_SERVER_URL)%'

    App\Infrastructure\Controller\ArgumentResolver\:
        resource: '%kernel.project_dir%/src/Infrastructure/Controller/ArgumentResolver'
        arguments:
            $serializer: '@serializer'
            $validator: '@validator'
        tags: ['controller.argument_value_resolver']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
